@startuml
left to right direction
rectangle "Портативный банкомат с доставкой" {
    (Ввести желаемую сумму наличных для снятия) as (UC1)
(Уведомление о размере комиссии) as (UC2)
( Уведомление об отсутствии суммы в терминал и предложение изменить/ввести иную сумму) as (UC2.1a)
( Уведомление об отсутствии купюр в терминале и предложение изменить/ввести иную сумму) as (UC2.1b)
(Cоглашается на изменение суммы.Переход на п1 основного сценарияу) as (UC2.2a)
(Соглаcиться с размером комиссии) as (UC3)
(Проверка наличия суммы снятия+суммы комиссии на карте) as (UC4)
(Запрос о необходимости распечатать чек) as (UC5)
( Уведомление об отсутствии достаточной суммы на карте и предложение изменить/ввести иную сумму) as (UC5.1)
(Подтверждает необходимость распечатки чека) as (UC6)
(Списание комисии и денежных средств с карты) as (UC7)
(Выдача денежных средства) as (UC8) 
(Печать чека об операции) as (UC9)
}
: Пользователь: as 1
1 --> UC1 
UC1 .> UC2 : includes
1 ---> UC3
UC1 <... UC3 : extends
UC3 .> UC5 : includes
UC5 <... UC6 : extends
UC3 .> UC4 : includes
UC4 <... UC7 : extends
1 ----> UC6
UC7 ...> UC8 : includes
UC6 ...> UC9 : includes
UC2 <. UC2.1a : extends
UC2 <.. UC2.1b : extends
UC1 <. UC2.2a : extends
UC2.2a <.. UC2.1a : extends
UC2.2a <.. UC2.1b : extends
UC2.2a <.. UC5.1 : extends
@enduml